# Generated by Django 5.0.1 on 2024-01-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
