# Generated by Django 5.0.1 on 2024-01-17 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_forget_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
